### ISSUE TITLE
geni-sync-wireless gets key error when syncing individual user

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1801]
When using the `--user` option to `geni-sync-wireless` we're getting a KeyError:

```
Traceback (most recent call last):
  File "/usr/bin/geni-sync-wireless", line 786, in <module>
    sys.exit(main())
  File "/usr/bin/geni-sync-wireless", line 782, in main
    wpm.synchronize()
  File "/usr/bin/geni-sync-wireless", line 340, in synchronize
    self.ensure_project_leads_are_group_admins()
  File "/usr/bin/geni-sync-wireless", line 514, in ensure_project_leads_are_group_admins
    lead_username = self._geni_members[lead_id]['username']
KeyError: '<UUID HERE>'
```

**Comment by tcmitchell** [comment]
The underlying issue seems to be that when a user is specified, only that user is fetched from the clearinghouse. Later when project leads are checked, their records are not in the user data, and that causes the KeyError. Skipping missing project leads seems to work fine. I'm waiting to test this with Orbit while they're watching their logs to make sure this still works on their side.
