### ISSUE TITLE
Handle or disallow project names with spaces

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#242]
I was able to create a project with a space in its name and this caused the slice page to fail to render the slice status table because it couldn't call `SliverStatus`. 

The log contains this error:
```
[Thu Sep 27 11:54:10 2012] [error] [client 128.89.80.18] am_client invoke_omni_function COMMAND = /usr/share/geni-ch/portal/gcf/src/omni_php.py -c /tmp/sedwards-omni.ini -l /usr/share/geni-ch/portal/gcf/src/logging.conf --logoutput /tmp/omni.log --api-version 2 --GetVersionCacheName /tmp/omniVersionCache2wFO4H --slicecredfile /tmp/sedwards.slicecredential sliverstatus urn:publicid:IDN+sergyar:slice1 test+slice+test, referer: https://sergyar.gpolab.bbn.com/secure/home.php?project_id=72b6cc76-bb5d-4b93-b18f-f4f016c0df0f&slice_id=955d3fc0-7fbc-40b7-8670-3dc980a18226&member_id=
```

If you look at this in detail the slice URN is invalid: 
```
urn:publicid:IDN+sergyar:slice1 test+slice+test
```

 _Imported from trac ticket [#242](http://trac.gpolab.bbn.com/proto-ch/ticket/242),  created by sedwards on 09-27-2012 at 12:00, last modified: 10-03-2012 at 15:11_

**Comment by ahelsing** [comment]
repeated the error now that DB inputs are being quoted.

logs:
```
[Tue Oct 02 16:37:11 2012] [error] [client 128.89.253.60] Call to sliver_status() FAILed, referer: https://illyrica.gpolab.bbn.com/secure/createslice.php?project_id=16201339-898f-4e46-8e77-0540386a53e4
[Tue Oct 02 16:44:21 2012] [error] [client 128.89.253.60] am_client invoke_omni_function COMMAND = /usr/share/geni-ch/portal/gcf/src/omni_php.py -c /tmp/ahelsing-omni.ini -l /usr/share/geni-ch/portal/gcf/src/logging.conf --logoutput /tmp/omni.log --api-version 2 --GetVersionCacheName /tmp/omniVersionCachehNqcJC --slicecredfile /tmp/ahelsing.slicecredential sliverstatus urn:publicid:IDN+illyrica:Aarons #&!*(@&$%&*!() project+slice+abettername, referer: https://illyrica.gpolab.bbn.com/secure/slice.php?slice_id=a6077664-ea48-4433-b9ea-4cc367b1b3e8
Traceback (most recent call last):
  File "/usr/share/geni-ch/portal/gcf/src/omni_php.py", line 51, in <module>
    sys.exit(main())
  File "/usr/share/geni-ch/portal/gcf/src/omni_php.py", line 38, in main
    text, obj = omni.call( args, options )
  File "/home/ahelsing/gcf-092412/src/omni.py", line 428, in call
    return API_call( framework, config, args, opts, verbose=verbose )
  File "/home/ahelsing/gcf-092412/src/omni.py", line 445, in API_call
    result = handler._handle(args)
  File "/home/ahelsing/gcf-092412/src/omnilib/handler.py", line 80, in _handle
    return getattr(self.amhandler, call)(args[1:])
  File "/home/ahelsing/gcf-092412/src/omnilib/amhandler.py", line 2379, in sliverstatus
    (name, urn, slice_cred, retVal, slice_exp) = self._args_to_slicecred(args, 1, "SliverStatus")
  File "/home/ahelsing/gcf-092412/src/omnilib/amhandler.py", line 3370, in _args_to_slicecred
    urn = self.framework.slice_name_to_urn(name)
  File "/home/ahelsing/gcf-092412/src/omnilib/frameworks/framework_gcf.py", line 92, in slice_name_to_urn
    urn = URN(None, None, None, name)
  File "/home/ahelsing/gcf-092412/src/geni/util/urn_util.py", line 61, in __init__
    self.type = urn_to_string_format(spl[2])
IndexError: list index out of range
[Tue Oct 02 16:44:21 2012] [error] [client 128.89.253.60] am_client invoke_omni_function:JSON result is not parseable: "", referer: https://illyrica.gpolab.bbn.com/secure/slice.php?slice_id=a6077664-ea48-4433-b9ea-4cc367b1b3e8
```


_Trac comment by ahelsing on 10-02-2012 at 16:46_
