### ISSUE TITLE
OBE: pgch shows error messages

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#459]
During Advanced Tutorial when clients are doing omni commands we're seeing:
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/SocketServer.py", line 281, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.6/SocketServer.py", line 307, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.6/SocketServer.py", line 320, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.6/SocketServer.py", line 615, in __init__
    self.handle()
  File "/usr/lib/python2.6/BaseHTTPServer.py", line 329, in handle
    self.handle_one_request()
  File "/usr/lib/python2.6/BaseHTTPServer.py", line 323, in handle_one_request
    method()
  File "/usr/lib/python2.6/SimpleXMLRPCServer.py", line 490, in do_POST
    self.send_response(200)
  File "/usr/lib/python2.6/BaseHTTPServer.py", line 382, in send_response
    (self.protocol_version, code, message))
  File "/usr/lib/python2.6/socket.py", line 300, in write
    self.flush()
  File "/usr/lib/python2.6/socket.py", line 286, in flush
    self._sock.sendall(buffer)
  File "/usr/lib/python2.6/ssl.py", line 203, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.6/ssl.py", line 94, in <lambda>
    self.send = lambda data, flags=0: SSLSocket.send(self, data, flags)
  File "/usr/lib/python2.6/ssl.py", line 174, in send
    v = self._sslobj.write(data)
error: [Errno 104] Connection reset by peer
```

 _Imported from trac ticket [#459](http://trac.gpolab.bbn.com/proto-ch/ticket/459),  created by ahelsing on 03-20-2013 at 16:49, last modified: 12-05-2013 at 13:19_

**Comment by ahelsing** [comment]
possibly related:
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/SocketServer.py", line 281, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.6/SocketServer.py", line 307, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.6/SocketServer.py", line 320, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.6/SocketServer.py", line 614, in __init__
    self.setup()
  File "/home/tmitchel/gcf-4094de01de/src/geni/SecureXMLRPCServer.py", line 52, in setup
    self.server.peercert = self.request.getpeercert()
  File "/usr/lib/python2.6/ssl.py", line 157, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
AttributeError: 'NoneType' object has no attribute 'peer_certificate'
```


_Trac comment by ahelsing on 03-20-2013 at 16:49_

**Comment by ahelsing** [comment]
We suspect this is due to poor wireless connectivity, breaking the SSL connection. Can we be robust to this in any way?

_Trac comment by ahelsing on 03-26-2013 at 10:21_
