### ISSUE TITLE
Fix tracebacks in omni_php.py when creating a sliver fails

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#649]
When a sliver cannot be created, `omni_php.py` does not exit cleanly. This information is later passed to `am_client.php` and `createsliver.php` where it had previously displayed a blank blue box (but now displays the whole traceback in #444). This should be cleaned up in some way such that either 1) the user does not explicitly see the traceback but knows that an error exists or 2) there should be a modification to the code to prevent a traceback.

An example when requesting Northwestern InstaGENI resources from cascade:
```
Traceback (most recent call last):
File "/usr/share/geni-ch/portal/gcf/src/omni_php.py", line 51, in
sys.exit(main())
File "/usr/share/geni-ch/portal/gcf/src/omni_php.py", line 38, in main
text, obj = omni.call( args, options )
File "/usr/share/geni-ch/portal/gcf-2.2.1/src/omni.py", line 446, in call
return API_call( framework, config, args, opts, verbose=verbose )
File "/usr/share/geni-ch/portal/gcf-2.2.1/src/omni.py", line 463, in API_call
result = handler._handle(args)
File "/usr/share/geni-ch/portal/gcf-2.2.1/src/omnilib/handler.py", line 83, in _handle
(message, val) = getattr(self.amhandler,call)(args[1:])
File "/usr/share/geni-ch/portal/gcf-2.2.1/src/omnilib/amhandler.py", line 1655, in createsliver
self._raise_omni_error("Cannot CreateSliver at %s: The AM speaks the wrong API version, not %d. %s" % 
(client.url, self.opts.api_version, bce.validMsg))
File "/usr/share/geni-ch/portal/gcf-2.2.1/src/omnilib/amhandler.py", line 4284, in _raise_omni_error
raise err, msg
omnilib.util.omnierror.OmniError: Cannot CreateSliver at https://boss.instageni.northwestern.edu:12369/
protogeni/xmlrpc/am/2.0: The AM speaks the wrong API version, not 2. Got no api_version from getversion 
at https://boss.instageni.northwestern.edu:12369/protogeni/xmlrpc/am/2.0? AM 
https://boss.instageni.northwestern.edu:12369/protogeni/xmlrpc/am/2.0 
failed getversion (empty): Server does not trust the CA (4811d309-bc04-4726-b2e7-408d63848087) 
that signed your (urn:publicid:IDN+ch1.gpolab.bbn.com+user+bujcich) user certificate! Use an account at 
another clearinghouse or find another server. ... skipped this aggregate
```

 _Imported from trac ticket [#649](http://trac.gpolab.bbn.com/proto-ch/ticket/649),  created by bujcich on 06-24-2013 at 14:39, last modified: 07-10-2013 at 01:24_

**Comment by ahelsing** [comment]
Fixed for now; merged to `develop-gec17`. In `createsliver.php`, the traceback display was removed. The line beginning with `omnilib.util.omnierror` from the traceback is displayed to the user along with a message that explicitly says that sliver creation failed.

_Trac comment by bujcich on 07-03-2013 at 16:21_
