### ISSUE TITLE
OBE: traceback in pgch: python bug on failed SSL connections

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#702]
During the GEMINI scaling tests this afternoon I see a traceback in the pgch logs

```
[Wed Jul 10 14:38:56 2013] [INFO] gcf-pgch: Already had keys for 'eec1ec5f-70e0-46fd-b948-6852e07dcd7c'
[Wed Jul 10 14:38:56 2013] [INFO] gcf-pgch: Calling lookup_slice_by_urn(urn:publicid:IDN+ch.geni.net:GIMI
Testing+slice+gimi-test) for ch\.geni\.net.cwang1 (eec1ec5f-70e0-46fd-b948-6852e07dcd7c)
[Wed Jul 10 14:38:56 2013] [INFO] gcf-pgch: Already had keys for 'eec1ec5f-70e0-46fd-b948-6852e07dcd7c'
[Wed Jul 10 14:38:56 2013] [INFO] gcf-pgch: Calling lookup_slice_by_urn(urn:publicid:IDN+ch.geni.net:GIMI
Testing+slice+gimi-test) for ch\.geni\.net.cwang1 (eec1ec5f-70e0-46fd-b948-6852e07dcd7c)
[Wed Jul 10 14:38:57 2013] [INFO] gcf-pgch: Found slice id 1c4a8ec8-42e6-4a71-b42a-cedbdbc142ae for urn u
rn:publicid:IDN+ch.geni.net:GIMITesting+slice+gimi-test
[Wed Jul 10 14:38:57 2013] [INFO] gcf-pgch: Already had keys for 'eec1ec5f-70e0-46fd-b948-6852e07dcd7c'
[Wed Jul 10 14:38:57 2013] [INFO] gcf-pgch: Calling get_slice_credential(1c4a8ec8-42e6-4a71-b42a-cedbdbc1
42ae) for ch\.geni\.net.cwang1 (eec1ec5f-70e0-46fd-b948-6852e07dcd7c)
[Wed Jul 10 14:39:00 2013] [INFO] gcf-pgch: Already had keys for 'eec1ec5f-70e0-46fd-b948-6852e07dcd7c'
[Wed Jul 10 14:39:00 2013] [INFO] gcf-pgch: Calling lookup_slices(eec1ec5f-70e0-46fd-b948-6852e07dcd7c) f
or ch\.geni\.net.cwang1 (eec1ec5f-70e0-46fd-b948-6852e07dcd7c)
Traceback (most recent call last):
  File "/usr/lib/python2.6/SocketServer.py", line 558, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.6/SocketServer.py", line 320, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.6/SocketServer.py", line 614, in __init__
    self.setup()
  File "/usr/share/geni-ch/portal/gcf-2.2.1-threading-ticket313/src/geni/SecureThreadedXMLRPCServer.py", 
line 49, in setup
    SecureXMLRPCRequestHandler.setup(self)
  File "/usr/share/geni-ch/portal/gcf-2.2.1-threading-ticket313/src/geni/SecureXMLRPCServer.py", line 52,
 in setup
    self.server.peercert = self.request.getpeercert()
  File "/usr/lib/python2.6/ssl.py", line 157, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
AttributeError: 'NoneType' object has no attribute 'peer_certificate'
Traceback (most recent call last):
  File "/usr/lib/python2.6/SocketServer.py", line 558, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.6/SocketServer.py", line 320, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.6/SocketServer.py", line 614, in __init__
    self.setup()
  File "/usr/share/geni-ch/portal/gcf-2.2.1-threading-ticket313/src/geni/SecureThreadedXMLRPCServer.py", 
line 49, in setup
    SecureXMLRPCRequestHandler.setup(self)
  File "/usr/share/geni-ch/portal/gcf-2.2.1-threading-ticket313/src/geni/SecureXMLRPCServer.py", line 52,
 in setup
    self.server.peercert = self.request.getpeercert()
  File "/usr/lib/python2.6/ssl.py", line 157, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
AttributeError: 'NoneType' object has no attribute 'peer_certificate'
[Wed Jul 10 14:39:49 2013] [INFO] gcf-pgch: Already had keys for 'eec1ec5f-70e0-46fd-b948-6852e07dcd7c'
[Wed Jul 10 14:39:49 2013] [INFO] gcf-pgch: Calling lookup_slices(eec1ec5f-70e0-46fd-b948-6852e07dcd7c) f
or ch\.geni\.net.cwang1 (eec1ec5f-70e0-46fd-b948-6852e07dcd7c)
[Wed Jul 10 14:39:53 2013] [INFO] gcf-pgch: Already had keys for 'eec1ec5f-70e0-46fd-b948-6852e07dcd7c'
[Wed Jul 10 14:39:53 2013] [INFO] gcf-pgch: Calling lookup_slice_by_urn(urn:publicid:IDN+ch.geni.net:GEMI
NIScalability+slice+congGenimiscale) for ch\.geni\.net.cwang1 (eec1ec5f-70e0-46fd-b948-6852e07dcd7c)
```

and later

```
[Wed Jul 10 15:24:08 2013] [INFO] gcf-pgch: Already had keys for '1e8a6584-208b-4f91-a79e-4054b6d3033c'
[Wed Jul 10 15:24:08 2013] [INFO] gcf-pgch: Calling lookup_slice_by_urn(urn:publicid:IDN+ch.geni.net:GEMI
NIScalability+slice+wesleygemini) for ch\.geni\.net.xiongqi (1e8a6584-208b-4f91-a79e-4054b6d3033c)
[Wed Jul 10 15:24:08 2013] [INFO] gcf-pgch: Already had keys for '1e8a6584-208b-4f91-a79e-4054b6d3033c'
[Wed Jul 10 15:24:08 2013] [INFO] gcf-pgch: Calling lookup_slice_by_urn(urn:publicid:IDN+ch.geni.net:GEMI
NIScalability+slice+wesleygemini) for ch\.geni\.net.xiongqi (1e8a6584-208b-4f91-a79e-4054b6d3033c)
[Wed Jul 10 15:24:08 2013] [INFO] gcf-pgch: Found slice id 279df0d5-5181-4e9d-b881-3eef4bf416a5 for urn u
rn:publicid:IDN+ch.geni.net:GEMINIScalability+slice+wesleygemini
[Wed Jul 10 15:24:08 2013] [INFO] gcf-pgch: Already had keys for '1e8a6584-208b-4f91-a79e-4054b6d3033c'
[Wed Jul 10 15:24:08 2013] [INFO] gcf-pgch: Calling get_slice_credential(279df0d5-5181-4e9d-b881-3eef4bf4
16a5) for ch\.geni\.net.xiongqi (1e8a6584-208b-4f91-a79e-4054b6d3033c)
Traceback (most recent call last):
  File "/usr/lib/python2.6/SocketServer.py", line 558, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.6/SocketServer.py", line 320, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.6/SocketServer.py", line 614, in __init__
    self.setup()
  File "/usr/share/geni-ch/portal/gcf-2.2.1-threading-ticket313/src/geni/SecureThreadedXMLRPCServer.py", 
line 49, in setup
    SecureXMLRPCRequestHandler.setup(self)
  File "/usr/share/geni-ch/portal/gcf-2.2.1-threading-ticket313/src/geni/SecureXMLRPCServer.py", line 52,
 in setup
    self.server.peercert = self.request.getpeercert()
  File "/usr/lib/python2.6/ssl.py", line 157, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
AttributeError: 'NoneType' object has no attribute 'peer_certificate'
[Wed Jul 10 15:25:09 2013] [INFO] gcf-pgch: Already had keys for '1e8a6584-208b-4f91-a79e-4054b6d3033c'
[Wed Jul 10 15:25:09 2013] [INFO] gcf-pgch: Calling get_services_of_type(0=AM) for ch\.geni\.net.xiongqi 
(1e8a6584-208b-4f91-a79e-4054b6d3033c)
[Wed Jul 10 15:25:09 2013] [INFO] gcf-pgch: ListComponents returning 10 entries
```

 _Imported from trac ticket [#702](http://trac.gpolab.bbn.com/proto-ch/ticket/702),  created by ahelsing on 07-10-2013 at 15:42, last modified: 12-05-2013 at 13:20_

**Comment by ahelsing** [comment]
http://bugs.python.org/issue13721

The SSL library has a bug that when the SSL handshake fails partway through it fails in this ugly way.

There are workarounds, but none I've seen yet that people use in the XMLRPC python library.

I believe I have code that detects the issue. But I don't know how to handle it. Since the bug is detected in setup() and before request().

Some code that detects probably correctly but doesn't have the right response for SecureXMLRPCRequestHandler (to be duplicated in SecureThreadedXMLRPCRequestHandler)
```
        self.request_version = self.default_request_version;
        self.command = 'GET';

        if self.request.cipher(): # http://bugs.python.org/issue13721
            msg = "Failed SSL Connection. Server busy: wait and try again."
            self.send_response(503, msg) # service unavailable, retry. alternative would be 408 request timeout
            self.send_header("Content-type", "text/plain")
            self.send_header("Content-length", str(len(msg)))
            self.end_headers()
            self.wfile.write(msg)
            self.close_connection = 1
            #return
            raise Exception("Failed SSL connection")

        try:
            # This first is humanreadable subjectAltName URI, etc
            self.server.peercert = self.request.getpeercert()
            self.server.der_cert = self.request.getpeercert(binary_form=True)
        except AttributeError:
            self.send_error(503, "Failed SSL Connection. Server busy: wait and try again.") # service unavailable, retry. alternative would be 408 request timeout
            #raise Exception("Failed SSL connection")
        except OSError:
            # This is python 3.4+ behavior
            self.send_error(503, "Failed SSL Connection. Server busy: wait and try again.") # service unavailable, retry. alternative would be 408 request timeout
            #raise

        if self.server.der_cert is None:
            self.send_error(503, "Failed SSL Connection (no user certificate found). Server busy: wait and try again.") # service unavailable, retry. alternative would be 408 request timeout
            #raise Exception("Failed SSL connection: no user certificate found")
```


_Trac comment by ahelsing on 07-11-2013 at 14:56_
